# """
# Django settings for hospital project.

# Generated by 'django-admin startproject' using Django 6.0.1.

# For more information on this file, see
# https://docs.djangoproject.com/en/6.0/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/6.0/ref/settings/
# """

# import os
# from pathlib import Path

# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent


# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = "django-insecure-i!y^_u(7%7s64tl0umdyaaoy!a-34+h+k#+md$#%p77tg%-e&3"

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG =False

# ALLOWED_HOSTS = [
#     "localhost",
#     "127.0.0.1",
#     ".onrender.com",  # <-- your actual Render domain
# ]
    


# # Application definition


# INSTALLED_APPS = [
#     "jazzmin",
#     "django.contrib.admin",
#     "django.contrib.auth",
#     "django.contrib.contenttypes",
#     "django.contrib.sessions",
#     "django.contrib.messages",
#     "django.contrib.staticfiles",
#     "hp_management",
#     "authentication",
# ]

# MIDDLEWARE = [
#     "django.middleware.security.SecurityMiddleware",
#     "whitenoise.middleware.WhiteNoiseMiddleware",  # Add this
#     "django.contrib.sessions.middleware.SessionMiddleware",
#     "django.middleware.common.CommonMiddleware",
#     "django.middleware.csrf.CsrfViewMiddleware",
#     "django.contrib.auth.middleware.AuthenticationMiddleware",
#     "django.contrib.messages.middleware.MessageMiddleware",
#     "django.middleware.clickjacking.XFrameOptionsMiddleware",
# ]


# ROOT_URLCONF = "hospital.urls"

# TEMPLATES = [
#     {
#         "BACKEND": "django.template.backends.django.DjangoTemplates",
#         "DIRS": [os.path.join(BASE_DIR, "templates")],
#         "APP_DIRS": True,
#         "OPTIONS": {
#             "context_processors": [
#                 "django.template.context_processors.request",
#                 "django.contrib.auth.context_processors.auth",
#                 "django.contrib.messages.context_processors.messages",
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = "hospital.wsgi.application"


# # Database
# # https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# TIME_ZONE = "Asia/Kolkata"


# import dj_database_url

# DATABASES = {
#     "default": dj_database_url.parse(
#         "postgresql://neondb_owner:npg_9rvMTS3OEyac@ep-little-boat-a1hzxceg-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
#     )
# }


# # Password validation
# # https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
#     },
#     {
#         "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
#     },
#     {
#         "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
#     },
#     {
#         "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
#     },
# ]


# # Internationalization
# # https://docs.djangoproject.com/en/6.0/topics/i18n/

# LANGUAGE_CODE = "en-us"

# TIME_ZONE = "UTC"

# USE_I18N = True

# USE_TZ = True


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/6.0/howto/static-files/


# STATIC_URL = "static/"
# STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
# STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# MEDIA_URL = "/media/"
# MEDIA_ROOT = os.path.join(BASE_DIR, "media")
# # Optional: enable compression and caching
# STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# # EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# # EMAIL_HOST = "smtp.gmail.com"
# # EMAIL_PORT = 587
# # EMAIL_USE_TLS = True
# # EMAIL_HOST_USER = "akashdhaigude1907@gmail.com"
# # EMAIL_HOST_PASSWORD = "krtxyzyhxeegdqda"
# # DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# import os

# # ================= EMAIL (PRODUCTION - SENDGRID) =================

# # EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# # EMAIL_HOST = "smtp.sendgrid.net"
# # EMAIL_PORT = 587
# # EMAIL_USE_TLS = True

# # EMAIL_HOST_USER = "apikey"
# # EMAIL_HOST_PASSWORD = os.environ.get("SENDGRID_API_KEY")

# # DEFAULT_FROM_EMAIL = "akashdhaigude1907@gmail.com"


# if not DEBUG:
#     EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
#     EMAIL_HOST = "smtp.sendgrid.net"
#     EMAIL_PORT = 587
#     EMAIL_USE_TLS = True
#     EMAIL_HOST_USER = "apikey"
#     EMAIL_HOST_PASSWORD = os.environ.get("SENDGRID_API_KEY")
#     DEFAULT_FROM_EMAIL = "akashdhaigude1907@gmail.com"


# JAZZMIN_SETTINGS = {
#     "site_title": "Hospital Admin",
#     "site_brand": "Hospital Management System",
#     "welcome_sign": "Welcome to Hospital Admin Panel",
#     "show_sidebar": True,
#     "navigation_expanded": True,
#     "custom_css": "css/jazzmin_custom.css",
# }

# # ================= LOCAL DEVELOPMENT =================
# # if DEBUG:
# #     EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
# #     DEFAULT_FROM_EMAIL = "akashdhaigude1907@gmail.com"


import os
from pathlib import Path
import dj_database_url

BASE_DIR = Path(__file__).resolve().parent.parent

# =======================
# SECURITY
# =======================
SECRET_KEY = os.environ.get("SECRET_KEY")
DEBUG = os.environ.get("DEBUG", "False") == "True"
ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "").split(",")

# =======================
# Applications
# =======================
INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "hp_management",
    "authentication",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "hospital.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "hospital.wsgi.application"

# =======================
# Database
DATABASE_URL = os.environ.get("DATABASE_URL")

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# =======================
# Internationalization
# =======================
LANGUAGE_CODE = "en-us"
TIME_ZONE = "Asia/Kolkata"
USE_I18N = True
USE_TZ = True

# =======================
# Static & Media Files
# =======================
STATIC_URL = "/static/"
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# =======================
# Email (SendGrid)
# =======================
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.sendgrid.net"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "apikey"
EMAIL_HOST_PASSWORD = os.environ.get("SENDGRID_API_KEY")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL")

# =======================
# Jazzmin Admin Theme
# =======================
JAZZMIN_SETTINGS = {
    "site_title": "Hospital Admin",
    "site_brand": "Hospital Management System",
    "welcome_sign": "Welcome to Hospital Admin Panel",
    "show_sidebar": True,
    "navigation_expanded": True,
    "custom_css": "css/jazzmin_custom.css",
}
