# Generated by Django 6.0.1 on 2026-02-06 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_passwordresetotp_otp'),
    ]

    operations = [
    ]
