# Generated by Django 6.0.1 on 2026-02-06 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20260206_1340'),
    ]

    operations = [
    ]
